"""Contracts shared by local classification, fallback policy, and preview."""

from .calibrated_policy import (
    CALIBRATED_POLICY_VERSION,
    DEFAULT_CALIBRATED_POLICY_PATH,
    GEMMA_ACCURACY_TARGET,
    LOCAL_PRECISION_TARGET,
    AxisCalibrationReport,
    CalibratedPolicy,
    CalibrationTargets,
    HeldOutAxisResult,
    PolicyCalibrationReport,
    calibrate_axis,
    calibrate_policy,
    load_calibrated_policy,
)
from .e5 import (
    E5_MODEL_ID,
    E5_RANKING_POLICY_VERSION,
    E5_VECTOR_SIZE,
    E5SubjectClassifier,
    FastEmbedE5Encoder,
    SubjectTextEncoder,
)
from .policy import AxisRoutingDecision, PolicyRoute, RoutingThresholds, route_axis
from .result import (
    AxisDecision,
    CandidateScore,
    DecisionSource,
    EducationalClassificationResult,
    EvidenceContribution,
    OrganizationPlan,
    Template,
)
from .subject import (
    DEFAULT_SUBJECT_PROFILES_PATH,
    SUBJECT_PROFILE_VERSION,
    SubjectClassifier,
    SubjectEvidence,
    SubjectProfile,
    eligible_subject_profiles,
    load_subject_profiles,
)
from .template import (
    DEFAULT_TEMPLATE_PROFILES_PATH,
    TEMPLATE_PROFILE_VERSION,
    TEMPLATE_RANKING_POLICY_VERSION,
    TemplateClassifier,
    TemplateEvidence,
    TemplateEvidenceWeights,
    TemplateProfile,
    TemplateTextEncoder,
    load_template_profiles,
    ordered_template_profiles,
)

__all__ = [
    "AxisRoutingDecision",
    "AxisCalibrationReport",
    "AxisDecision",
    "CALIBRATED_POLICY_VERSION",
    "CalibratedPolicy",
    "CalibrationTargets",
    "CandidateScore",
    "DecisionSource",
    "DEFAULT_SUBJECT_PROFILES_PATH",
    "DEFAULT_CALIBRATED_POLICY_PATH",
    "DEFAULT_TEMPLATE_PROFILES_PATH",
    "E5_MODEL_ID",
    "E5_RANKING_POLICY_VERSION",
    "E5_VECTOR_SIZE",
    "E5SubjectClassifier",
    "EducationalClassificationResult",
    "EvidenceContribution",
    "FastEmbedE5Encoder",
    "GEMMA_ACCURACY_TARGET",
    "HeldOutAxisResult",
    "LOCAL_PRECISION_TARGET",
    "OrganizationPlan",
    "PolicyRoute",
    "PolicyCalibrationReport",
    "RoutingThresholds",
    "SubjectClassifier",
    "SubjectEvidence",
    "SubjectProfile",
    "SUBJECT_PROFILE_VERSION",
    "SubjectTextEncoder",
    "Template",
    "TemplateClassifier",
    "TemplateEvidence",
    "TemplateEvidenceWeights",
    "TemplateProfile",
    "TEMPLATE_PROFILE_VERSION",
    "TEMPLATE_RANKING_POLICY_VERSION",
    "TemplateTextEncoder",
    "eligible_subject_profiles",
    "calibrate_axis",
    "calibrate_policy",
    "load_calibrated_policy",
    "load_subject_profiles",
    "load_template_profiles",
    "ordered_template_profiles",
    "route_axis",
]
